from datetime import datetime
import os


def generate_html_report(scan_result):
    scan_time = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
    total_ports = len(scan_result["results"])
    total_cves = 0
    critical = 0
    high = 0
    medium = 0
    low = 0

    for result in scan_result["results"]:
        for vuln in result["vulnerabilities"]:

            total_cves += 1
            severity = vuln["severity"].upper()
            if severity == "CRITICAL":
                critical+=1
            elif severity == "HIGH":
                high+=1
            elif severity == "MEDIUM":
                medium+=1
            elif severity == "LOW":
                low+=1

    html = f""" 
    <!DOCTYPE html>
            <html lang="en">
            <head>
            <meta charset="UTF=8">
            <title>VulnScanX Report</title>
            <link rel="stylesheet" href="style.css">
            </head>

            <body>
            <div class="container">
            <h1>VulnScanX</h1>
            <h2>Network Vulnerability Scan Report</h2>
            <hr>
            <h3>Scan Information</h3>
            <p><strong>Target:</strong> {scan_result["target"]}<p>
            <p><strong>Scan Time:</strong>{scan_time}</p>
            
            <div class="summary">

            <div class="card">
            <h3>{total_ports}</h3>
            <p>open ports</p>
            </div>

            <div class="card">
            <h3>{total_cves}</h3>
            <p>Total CVEs</p>
            </div>

            <div class="card critical">
            <h3>{critical}</h3>
            <p>Critical</p>
            </div>

            <div class="card high">
            <h3>{high}</h3>
            <p>High</p>
            </div>

            <div class="card medium">
            <h3>{medium}</h3>
            <p>Medium</p>
            </div>

            <div class="card low">
            <h3>{low}</h3>
            <p>Low</p>
            </div>        




            </div>
        
            <hr>

            <h2>Open Ports</h2>
            <table border="1" cellspacing="0" cellpadding="8">
            <tr>
            <th class="center">Port</th>
            <th>Service</th>
            <th>Banner</th>
            <th>Software</th>
            <th>Version</th>
            </tr>
            """
    for result in scan_result["results"]:
        html+= f"""
        <tr>
        <td class="center">{result["port"]}</td>
        <td>{result["service"]}</td>
        <td>{result["banner"]}</td>
        <td>{result["software"]}</td>
        <td>{result["version"]}</td>
        </tr>
        """
    
    html+="""
    </table>
    <br>
    <hr>
    """

    html+="""
    <h2>Vulnerabilities</h2>
    """

    for result in scan_result["results"]:
        if len(result["vulnerabilities"]) != 0:
            html+= f"""
            <h3>Port {result["port"]} ({result["service"]})</h3>
            """
        
        if len(result["vulnerabilities"]) == 0:
            # html+= """
            # <p>No known vulnerabilities found.</p>
            # """
            pass
        else:
            for vuln in result["vulnerabilities"]:
                html+=f"""
                <div class="vuln-card">
                <h4>{vuln["cve"]}</h4>
                <p>
                <strong>Severity:</strong> 
                <span class="badge {vuln["severity"].lower()}">
                {vuln["severity"]}
                </span>
                </p>
                <p><strong>CVSS Score:</strong> {vuln["score"]}</p>
                <p><strong>Description:</strong></p>
                <p>{vuln["description"]}</p>
                </div>
                """


    html+=f"""
    <hr>
    <footer>
    <p>Generated by <strong>VulnScanX</strong></p>
    <p>Report Generated: {scan_time}</p>
    </footer>
    """
    



    html+=f"""
    </div>
    </body>
    </html>
    """



    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    REPORT_PATH = os.path.join(BASE_DIR, "report.html")

    with open(REPORT_PATH, "w", encoding="utf-8") as file:
        file.write(html)

    print(f"HTML saved at {REPORT_PATH}") 

    